# Generated by Django 5.0.6 on 2024-07-16 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='invoiceHeader',
            fields=[
                ('UUID', models.IntegerField(unique=True)),
                ('date', models.DateTimeField()),
                ('invoiceNumber', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=50)),
                ('billingAddress', models.CharField(max_length=100)),
                ('shippingAddress', models.CharField(max_length=100)),
                ('GSTIN', models.CharField(max_length=100)),
                ('totalAmount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='invoiceBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billName', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('UUID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codinground.invoiceheader')),
            ],
        ),
        migrations.CreateModel(
            name='invoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('amount', models.FloatField()),
                ('UUID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codinground.invoiceheader')),
            ],
        ),
    ]
